### PR TITLE
Improvements and I added Polish translation

### PR DESCRIPTION
**Pull request by xdk78**

### CODE REVIEW

**Comment by xdk78** [comment]
This commad making error in Travic build `The command "openssl aes-256-cbc -K $encrypted_7045a360e0b4_key -iv $encrypted_7045a360e0b4_iv -in keystore.jks.enc -out keystore.jks -d" failed and exited with 1 during .`

**Comment by akuma06** [comment]
Will check on our end if openssl works

**Comment by akuma06** [comment]
Ok, I will try to fix travis and make another test for this PR :)

**Comment by xdk78** [comment]
It seems that now there are no errors 👍

**Pull request merged**
