### PR TITLE
Added anime streaming, code improvements

### PR DESCRIPTION
**Pull request by xdk78**
https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/5

### CODE REVIEW

**Comment by xdk78** [comment]
What do you think about this?

**Comment by akuma06** [comment]
I tried the stream option, however every time I launch a video, it starts playing and stops. Do you have any idea?

After investigating a bit, I think it might come from the fact that I can't read&play at the same time. I added TorrentStreamServer instead of directly using TorrentStream, what do you think?

Besides that I just finished the recent fragment. I will merge this in another branch and PR my changes. Take a look at it =)

**Comment by xdk78** [comment]
Ok, that's good idea.

**Comment by xdk78** [comment]
I tested some torrents only through the few seconds, torrent stream server looks good too

**Comment by xdk78** [comment]
Probably we need to keep app all time in memory(u know, Android life cycle and other shit) when streaming is started

**Pull request merged**
